[project]
authors = [{name = "dnth", email = "dickson.neoh@gmail.com"}]
description = "Simplify PostgreSQL search using Python."
name = "pgsql-search"
requires-python = ">= 3.11"
version = "0.1.0"
dependencies = ["psycopg>=3.2.3,<4", "loguru>=0.7.3,<0.8"]

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.pypi-dependencies]
pgsql_search = { path = ".", editable = true }

[tool.pixi.tasks]

[tool.pixi.dependencies]
postgresql = "<17"
pgvector = ">=0.7.4,<0.8"
